fixtures:
  repositories:
    rpcbind:
      repo: 'https://github.com/ghoneycutt/puppet-module-rpcbind.git'
      ref:  'v3.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '5.2.0'
  symlinks:
    nisclient: "#{source_dir}"
